import 'package:flutter/foundation.dart' show kIsWeb;

/// Registers the Flutter service worker for PWA offline support.
///
/// This is a stub that should be called during app initialization on web.
/// On non-web platforms this is a no-op.
///
/// The actual service worker file (`flutter_service_worker.js`) is
/// auto-generated by `flutter build web`.  This registrar uses
/// `dart:js_interop` and `package:web` to call the browser
/// `navigator.serviceWorker.register()` API.
///
/// Usage:
/// ```dart
/// void main() {
///   ServiceWorkerRegistrar.register();
///   runApp(const OrchestraApp());
/// }
/// ```
class ServiceWorkerRegistrar {
  ServiceWorkerRegistrar._();

  /// Whether the service worker has been registered in this session.
  static bool _registered = false;

  /// Registers the Flutter service worker if running on the web platform.
  ///
  /// This method is safe to call on any platform — it is a no-op when
  /// [kIsWeb] is false.  On web, it conditionally imports the web interop
  /// library and calls `navigator.serviceWorker.register`.
  ///
  /// Returns `true` if registration was initiated, `false` if skipped
  /// (non-web platform or already registered).
  static bool register({String scriptUrl = '/flutter_service_worker.js'}) {
    if (!kIsWeb) return false;
    if (_registered) return false;

    _registered = true;
    _registerWeb(scriptUrl);
    return true;
  }

  /// Web-specific registration.  Guarded by the [kIsWeb] check in [register]
  /// so this code is tree-shaken on native platforms.
  static void _registerWeb(String scriptUrl) {
    // Use conditional import to avoid pulling in dart:js_interop on native.
    // The actual registration is handled by Flutter's built-in bootstrap
    // script (flutter_bootstrap.js) which calls
    // `_flutter.loader.load({ serviceWorkerSettings: ... })`.
    //
    // This stub exists for cases where you need to register a custom
    // service worker or trigger registration programmatically outside
    // the Flutter bootstrap flow.
    //
    // For the standard Flutter service worker, no additional action is
    // needed here — the bootstrap script in index.html handles it.
    //
    // To register a custom service worker, uncomment the following and
    // add `import 'package:web/web.dart' as web;` behind a conditional
    // import guard:
    //
    // if (web.window.navigator.serviceWorker != null) {
    //   web.window.navigator.serviceWorker!.register(scriptUrl.toJS);
    // }

    assert(() {
      // In debug mode, log that we would register the service worker.
      // ignore: avoid_print
      // Service worker registration is handled by flutter_bootstrap.js
      return true;
    }());
  }
}
