// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS2QgWZy-hk3ibF_ZDdHUHOQl6qBc_jTA',
    appId: '1:873906913183:web:37520a14beb3ba7e61c7aa',
    messagingSenderId: '873906913183',
    projectId: 'orchestra-mcp-dev',
    authDomain: 'orchestra-mcp-dev.firebaseapp.com',
    storageBucket: 'orchestra-mcp-dev.firebasestorage.app',
    measurementId: 'G-8PN0VBEKL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCxKUiv3rG5gT6mesDp28dgvXI79_z6g',
    appId: '1:873906913183:android:9519d8009b0072fd61c7aa',
    messagingSenderId: '873906913183',
    projectId: 'orchestra-mcp-dev',
    storageBucket: 'orchestra-mcp-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt1AUZA8UEjbyLv0RD3gvODKR3v9ZKWDg',
    appId: '1:873906913183:ios:89f72c15e6eb745861c7aa',
    messagingSenderId: '873906913183',
    projectId: 'orchestra-mcp-dev',
    storageBucket: 'orchestra-mcp-dev.firebasestorage.app',
    iosBundleId: 'com.orchestramcp.orchestra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt1AUZA8UEjbyLv0RD3gvODKR3v9ZKWDg',
    appId: '1:873906913183:ios:89f72c15e6eb745861c7aa',
    messagingSenderId: '873906913183',
    projectId: 'orchestra-mcp-dev',
    storageBucket: 'orchestra-mcp-dev.firebasestorage.app',
    iosBundleId: 'com.orchestramcp.orchestra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS2QgWZy-hk3ibF_ZDdHUHOQl6qBc_jTA',
    appId: '1:873906913183:web:a5de296cb214138661c7aa',
    messagingSenderId: '873906913183',
    projectId: 'orchestra-mcp-dev',
    authDomain: 'orchestra-mcp-dev.firebaseapp.com',
    storageBucket: 'orchestra-mcp-dev.firebasestorage.app',
    measurementId: 'G-3R7Y7K3B17',
  );
}
